---
# defaults file for vpc-n-eks-remote-state
ansible_python_interpreter: /usr/bin/python3
haproxy_lb_remote_state_terraform_dir: "{{ playbook_dir }}/../terraform/aws/haproxy-autoscale/remote_state"
project_name: devops-it-all
