---
- name: Install helm consul chart on aws eks
  terraform:
    binary_path: "/home/{{ lookup('env','USER') }}/bin/terraform"
    #binary_path: "{{ user_home }}/bin/terraform"
    project_path: "{{ consul_helm_terraform_dir }}"
    state: present
    lock: yes
    backend_config:
      region: "us-east-1"
      bucket: "devopsitall-terraform-remote-state"
      key: "management-helm/consul-terraform.tfstate"
      dynamodb_table:  "devopsitall-helm-consul-terraform-remote-lock"
      encrypt: "true"
    force_init: true
  register: terraform_run

- name: consul helm Terraform output
  debug:
    msg:
      - "{{ terraform_run.command }}"
      - "{{ terraform_run.stdout }}"

