---
- name: management namespace create
  shell: kubectl create namespace management
  ignore_errors: true
- name: Install helm consul chart on aws eks
  block:
    - helm:
        chart:
          name: "{{ helm_name }}"
          version: "{{ helm_version }}"
          source:
            type: git
            location: "{{ helm_location }}"
        state: present
        values: "{{ lookup('file', 'consul-default-values-override-kubernetes.yml') | from_yaml }}"
        name: "consul-devopsitall"
        namespace: management
      register: consul_helm_install
  rescue:
    - debug:
        msg: "Consul cluster already exists" 

- name: Pause for 3 min wait for Consul helm chart build to complete ...
  pause:
    minutes: 3
  when: consul_helm_install.changed == true and consul_helm_install.failed == false
    
#- name: vault namespace create
  #shell: kubectl create namespace vault
  #ignore_errors: true
