---
# defaults file for elasticsearch-cluster---
ansible_python_interpreter: /usr/bin/python3
elasticsearch_helm_terraform_dir: "{{ playbook_dir }}/../terraform/aws/helm/elasticsearch"
project_name: devops-it-all
