---
- name: Create aws vpc with eks - it'll take about 10 min ...
  terraform:
    binary_path: "{{ user_home }}/bin/terraform"
    project_path: "{{ vpc_n_eks_terraform_dir }}"
    state: present 
    lock: yes
    backend_config:
      region: "us-east-1"
      bucket: "devopsitall-terraform-remote-state"
      key: "vpc-n-eks-terraform.tfstate"
      dynamodb_table:  "devopsitall-vpc-n-eks-terraform-remote-lock"
      encrypt: "true"
    #plan_file:    "{{ vpc_n_eks_terraform_dir }}/devops-it-all.tfplan"
    #state_file:   "{{ vpc_n_eks_terraform_dir }}/terraform.tfstate"
    force_init: true
  register: terraform_run

- name: Terraform output
  debug:
    msg: 
      - "{{ terraform_run.command }}"
      - "{{ terraform_run.stdout }}"

#- name: Update vault values.yaml with kmsid
  #replace:
    #dest="{{ playbook_dir }}/roles/vault-cluster/files/vault-values-on-kubernetes.yml"
    #regexp='(.*)(kms_key_id\s=\s)(.*)'
    #replace='\1\2{{ kmsid }}'

#- name: sleep for 300 seconds and continue with play when consul cluster deployment status is complete
  #wait_for:
    #timeout: 300

- name: Create user .kube dir
  file:
    path: "{{ user_home }}/.kube"
    state: directory
    mode: '0700'

- name: copy kubconfig file to user home .kube config file
  copy:
    src:  "{{ vpc_n_eks_terraform_dir }}/kubeconfig_kubernetes-{{ project_name }}"
    dest: "{{ user_home }}/.kube/config"
    owner: "{{ user_home.split('/')[-1] }}"
    group: "{{ user_home.split('/')[-1] }}"
    mode: "0600"
    force: yes
