---
- name: Check k8s secret eks-creds exists ?
  command: "{{ playbook_dir }}/../shell/eks-creds-k8s-secret-exists.sh"
  register: k8s_secret_aws_keys_exists

- name: If k8s secret aws_keys exists
  debug:
    msg: "k8s secret aws_keys exists"
  when: k8s_secret_aws_keys_exists.stdout|int > 0

- name: Add AWS key n secret to kubernets secret
  shell: "{{ playbook_dir }}/../shell/create-k8s-secret-aws-keys.sh"
  when: k8s_secret_aws_keys_exists.stdout|int == 0
  ignore_errors: true

