---
- name: Check k8s secret vault-tls exists ?
  command: "{{ playbook_dir }}/../shell/eks-creds-k8s-secret-exists.sh"
  register: k8s_secret_aws_keys_exists

- name: If k8s secret aws_keys exists
  debug:
    msg: "k8s secret aws_keys exists"
  when: k8s_secret_aws_keys_exists.stdout|int > 0

- name: Add AWS key n secret to kubernets secret
  shell: "{{ playbook_dir }}/../shell/create-k8s-secret-aws-keys.sh"
  when: k8s_secret_aws_keys_exists.stdout|int == 0
  ignore_errors: true

- name: Vault root token
  shell: "{{ playbook_dir }}/../shell/create-k8s-secret-vault.root.sh"
  ignore_errors: true


#- name: Create Secret
  #k8s:
    #state: present
    #force: true
    #resource_definition:
      #apiVersion: v1
      #kind: Secret
      #metadata:
        #name: eks-creds
        #namespace: default
      #type: Opaque
    #data:
      #AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
      ##AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
      #AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}" 
      ##AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}" 

