---
- name: Check k8s secret eks-creds exists ?
  command: "{{ playbook_dir }}/../shell/eks-creds-k8s-secret-exists.sh"
  register: k8s_secret_aws_keys_exists

- name: Add AWS key n secret to kubernets secret
  shell: "{{ playbook_dir }}/../shell/create-k8s-secret-aws-keys.sh"
  when: k8s_secret_aws_keys_exists.stdout|int == 0
  ignore_errors: true

