---
- name: Install helm vault chart on aws eks
  block:
    - helm:
        chart:
          name: vault-helm
          source:
            type: git
            location: https://github.com/hashicorp/vault-helm.git
        state: present
        values: "{{ lookup('file', 'vault-values-on-kubernetes.yml') | from_yaml }}"
        name: "vault-devopsitall"
        namespace: "vault"
      register: helm_vault_install
      ignore_errors: true
  rescue:
    - debug:
        msg: "Vault cluster already exists"

- name: Pause for 3 min wait for Vault helm chart build to complete ...
  pause:
    minutes: 3
  when: helm_vault_install.changed == true and helm_vault_install.failed == false

- name: Vault initialize & unseal
  shell: 'kubectl exec -it vault-devopsitall-0 -n vault vault operator init'
  register: vault_init_out
  ignore_errors: true
  no_log: True
