---
- name: Create Secret
  k8s:
    state: present
    force: true
    resource_definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: eks-creds
        namespace: default
      type: Opaque
    data:
      AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}" 

