---
- name: vault login and create jenkins secrets
  shell: |
    kubectl -n management exec -it vault-devopsitall-0 -c vault -- vault login '{{ root_token }}'
    kubectl cp '{{ local_user_home }}/.kube/config' management/vault-devopsitall-0:/tmp/mykubeconfig
    kubectl cp '{{ github_sshkey }}' management/vault-devopsitall-0:/tmp/mygithubsshkey
    kubectl cp {{ playbook_dir }}/roles/vault-cluster/files/jenkins_approle_policy.hcl management/vault-devopsitall-0:/tmp/jenkins_approle_policy.hcl
    kubectl -n management exec -it vault-devopsitall-0 -c vault -- vault secrets enable kv
    kubectl -n management exec -it vault-devopsitall-0 -c vault -- vault kv put /kv/jenkins-kubeconfig/appsecret mykubeconfig=@/tmp/mykubeconfig
    kubectl -n management exec -it vault-devopsitall-0 -c vault -- vault kv put /kv/jenkins/appsecret github_ssh_user_email='{{ github_ssh_user_email }}' \
                                                    github_ssh_priv_key=@/tmp/mygithubsshkey \
                                                    dockerhub_username='{{ dockerhub_username }}' \
                                                    dockerhub_password='{{ dockerhub_password }}'
    kubectl -n management exec -it vault-devopsitall-0 -c vault -- vault auth enable approle
    kubectl -n management exec -it vault-devopsitall-0 -c vault -- vault policy write jenkins /tmp/jenkins_approle_policy.hcl
    kubectl -n management exec -it vault-devopsitall-0 -c vault -- vault write auth/approle/role/jenkins policies=jenkins
    kubectl -n management exec -it vault-devopsitall-0 -c vault -- rm /tmp/mygithubsshkey /tmp/mykubeconfig /tmp/jenkins_approle_policy.hcl
  register: vault_login_n_secrets
  when: root_token is defined

- name: set facts jenkins vault role_id
  shell: |
    kubectl -n management exec vault-devopsitall-0 vault read auth/approle/role/jenkins/role-id | grep role_id | awk '{print $2}'
  register: role_id

- name: set facts jenkins vault secret_id
  shell: |
    kubectl -n management exec -it vault-devopsitall-0 -c vault -- vault write -f auth/approle/role/jenkins/secret-id | grep -w secret_id | grep secret_id | awk '{print $2}'
  register: secret_id

- name: set jenkins vault app role kubernetes secret
  shell: |
    kubectl -n management create secret generic jenkins-vault-app-role --from-literal='jenkinsVaultRoleID={{ role_id.stdout }}' --from-literal='jenkinsVaultRoleSecret={{ secret_id.stdout }}'
  when: root_token is defined

- name: Update Jenkins vault roleID
  replace:
    path: "{{ playbook_dir }}/../terraform/aws/helm/jenkins/override-values.yaml"
    regexp: >-
      (.*)appRoleID: .*, appRoleSecret(.*)?$
    replace: >-
      \1appRoleID: '{{ role_id.stdout }}', appRoleSecret\2
