---
- name: Install helm jenkins chart on aws eks
  block:
    - helm:
        chart:
          name: "{{ helm_name }}"
          version: "{{ helm_version }}"
          source:
            type: git
            location: "{{ helm_location }}"
            path: stable/jenkins
        state: present
        values: "{{ lookup('file', 'jenkins-values-on-kubernetes.yml') | from_yaml }}"
        name: "jenkins-devopsitall"
        namespace: "management"
      register: jenkins_helm_install
  rescue:
    - debug:
        msg: "jenkins helm chart already exists"

