---
- name: helm - Create terraform dynamoDB lock table
  terraform:
    binary_path: "/home/{{ lookup('env','USER') }}/bin/terraform"
    project_path: "{{ consul_helm_remote_state_terraform_dir }}"
    state:        present 
    force_init: true
  register: terraform_run

- name: Terraform output
  debug:
    msg: 
      - "{{ terraform_run }}"
