server:
  image:
    repository: "vault"
    tag: "1.3.3"
    pullPolicy: IfNotPresent
  updateStrategyType: "OnDelete"
  service:
    annotations:
      "consul.hashicorp.com/service-port": "http"
  extraSecretEnvironmentVars:
    - envName: AWS_ACCESS_KEY_ID
      secretName: eks-creds
      secretKey: AWS_ACCESS_KEY_ID
    - envName: AWS_SECRET_ACCESS_KEY
      secretName: eks-creds
      secretKey: AWS_SECRET_ACCESS_KEY
  extraVolumes:
    - type: secret
      name: vault-tls
      path: '/vault/userconfig'
  ha:
    enabled: true
    replicas: 3
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "127.0.0.1:8200"
        cluster_address = "127.0.0.1:8201"
      }
      listener "tcp" {
        address = "POD_IP:8200"
        cluster_address = "POD_IP:8201"
        tls_cert_file = "/vault/userconfig/vault-tls/vault.crt"
        tls_key_file  = "/vault/userconfig/vault-tls/vault.key"
        tls_disable_client_certs = true
      }
      seal "awskms" {
        region = "us-east-1"
        kms_key_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      }
      telemetry {
        prometheus_retention_time = "24h"
        disable_hostname = true
      }
      storage "consul" {
        path = "vault"
        address = "consul-devopsitall-server:8500"
      }
ui:
  enabled: true
injector:
  image:
    repository: "hashicorp/vault-k8s"
    tag: "0.3.0"
    pullPolicy: IfNotPresent
  agentImage:
    repository: "vault"
    tag: "1.3.3"
  # Mount Path of the Vault Kubernetes Auth Method.
  authPath: "auth/kubernetes"
  # Configures the log verbosity of the injector. Supported log levels: Trace, Debug, Error, Warn, Info
  logLevel: "info"
  # Configures the log format of the injector. Supported log formats: "standard", "json".
  logFormat: "standard"
  # Configures all Vault Agent sidecars to revoke their token when shutting down
  revokeOnShutdown: false
  certs:
    certName: vault.crt
    keyName: vault.key
