clusterName: "devopsitall-elasticsearch"
service:
  annotations:
    "consul.hashicorp.com/service-port": "http"
resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1024Mi"
esJavaOpts: "-Xmx256m -Xms256m"
