---
# defaults file for vault-helm-remote-state
ansible_python_interpreter: /usr/bin/python3
vault_helm_remote_state_terraform_dir: "{{ playbook_dir }}/../terraform/aws/helm/vault/remote_state"
project_name: devops-it-all
