---
- name: Install helm grafana chart on aws eks
  terraform:
    binary_path: "/home/{{ lookup('env','USER') }}/bin/terraform"
    project_path: "{{ grafana_helm_terraform_dir }}"
    state: present
    lock: yes
    backend_config:
      region: "us-east-1"
      bucket: "devopsitall-terraform-remote-state"
      key: "management-helm/grafana-terraform.tfstate"
      dynamodb_table:  "devopsitall-helm-grafana-terraform-remote-lock"
      encrypt: "true"
    force_init: true
  register: terraform_run
