---
- name: Create terraform dynamoDB lock table
  terraform:
    binary_path: "/home/{{ lookup('env','USER') }}/bin/terraform"
    project_path: "{{ haproxy_lb_remote_state_terraform_dir }}"
    state:        present 
    force_init: true
  register: terraform_run

- name: Terraform output
  debug:
    msg: 
      - "{{ terraform_run }}"

- name: Ansible-playbook automation sleep for 300 seconds until terraform s3 remote state  bucket is ready
  wait_for:
    timeout: 300
  when: terraform_run.changed and terraform_run.failed == false
