---
- name: management namespace create
  shell: kubectl create namespace management
  ignore_errors: true
- name: Create ssl dir for created crt and key files playbook ssl_created dir
  file:
    path: "{{ playbook_dir }}/../ssl_created"
    state: directory
    mode: '0700'
  register: ssl_dir

- name: Generate an OpenSSL private key (2048 bits, RSA)
  openssl_privatekey:
    path: "{{ ssl_dir.path }}/{{ item.name }}.key"
    size: 2048
  loop: "{{ management_apps }}"

- name: Generate management apps OpenSSL Certificate Signing Request
  openssl_csr:
    path: "{{ ssl_dir.path }}/{{ item.name }}.csr"
    privatekey_path: "{{ ssl_dir.path }}/{{ item.name }}.key"
    common_name: "{{ item.name }}"
    country_name: US
    locality_name: Washington
    state_or_province_name: CA
    organization_name: The Cloud
  loop: "{{ management_apps }}"

- name: Generate management apps Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{ ssl_dir.path }}/{{ item.name }}.crt"
    privatekey_path: "{{ ssl_dir.path }}/{{ item.name }}.key"
    csr_path: "{{ ssl_dir.path }}/{{ item.name }}.csr"
    provider: selfsigned
  loop: "{{ management_apps }}"
