---
- name: Check k8s secret apps tls exists ?
  command: "{{ playbook_dir }}/../shell/apps-tls-k8s-secret-exists.sh {{ item.name }}"
  loop: "{{ management_apps }}"
  ignore_errors: true
  register: ssl_exists

- name: If k8s secret ssl files exists ?
  debug:
    msg: "{{ item.item.name}}-tls ssl k8s secret exists"
  when: item.stdout|int > 0
  loop: "{{ ssl_exists.results }}"

- name: Add ssl key and crt as kubernets secret
  shell: "{{ playbook_dir }}/../shell/create-k8s-secret-app-ssl.sh {{ item.cmd[1]}}"
  when: item.stdout|int == 0
  loop: "{{ ssl_exists.results }}"

#- name: Create k8s secret for crt files
  #k8s:
    #kind: Secret
    #metadata:
      #name: vault_key
      #namespace: vault
    #type: Opaque
    #data:
      #- "{{ playbook_dir }}/ssl_created/vault.crt": vault.crt"
      #- "{{ playbook_dir }}/ssl_created/vault.key": vault.key"
    #state: present
 
#- name: Create k8s secret for crt files
   #k8s:
     #kind: secret
     #api_version: v1
     #metadata:
       #name: vault_key
       #namespace: default
     #type: Opaque
     #data:
       #"{{ playbook_dir }}/ssl_created/vault.crt": vault.crt
       #"{{ playbook_dir }}/ssl_created/vault.key": vault.key
     #state: present
