---
- name: Add ssl key and crt as kubernets secret
  shell: "{{ playbook_dir }}/../shell/create-k8s-secret-vault-tls.sh {{ playbook_dir }}/ssl_created/vault.crt  {{ playbook_dir }}/ssl_created/vault.key"

#- name: Create k8s secret for crt files
  #k8s:
    #kind: Secret
    #metadata:
      #name: vault_key
      #namespace: vault
    #type: Opaque
    #data:
      #- "{{ playbook_dir }}/ssl_created/vault.crt": vault.crt"
      #- "{{ playbook_dir }}/ssl_created/vault.key": vault.key"
    #state: present
 
#- name: Create k8s secret for crt files
   #k8s:
     #kind: secret
     #api_version: v1
     #metadata:
       #name: vault_key
       #namespace: default
     #type: Opaque
     #data:
       #"{{ playbook_dir }}/ssl_created/vault.crt": vault.crt
       #"{{ playbook_dir }}/ssl_created/vault.key": vault.key
     #state: present
