---
- name: Check k8s secret apps tls exists ?
  command: "{{ playbook_dir }}/../shell/apps-tls-k8s-secret-exists.sh {{ item.name }}"
  loop: "{{ management_apps }}"
  ignore_errors: true
  register: ssl_exists

- name: Add ssl key and crt as kubernets secret
  shell: "{{ playbook_dir }}/../shell/create-k8s-secret-app-ssl.sh {{ item.cmd[1]}}"
  when: item.stdout|int == 0
  loop: "{{ ssl_exists.results }}"
