kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: haproxy-ec2-role
  namespace: kube-system
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
      - "extensions"
    resources:
      - "configmaps"
      - "cronjobs"
      - "deployments"
      - "events"
      - "ingresses"
      - "jobs"
      - "pods"
      - "pods/attach"
      - "pods/exec"
      - "pods/log"
      - "pods/portforward"
      - "secrets"
      - "services"
    verbs:
      - "describe"
      - "get"
      - "list"
