kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-default-rolebinding
subjects:
- kind: User
  name: haproxy-ec2-user
roleRef:
  kind: Role
  name: haproxy-ec2-role
  apiGroup: rbac.authorization.k8s.io
