---
- hosts: localhost
  roles:
    - { role: devopsitall-prerequisite-cli, tags: prepare_management_server, become: yes }
    - { role: codecap.kubectl, tags: prepare_management_server }
    - { role: vpc-n-eks-remote-state, tags: first_time_run }
    - { role: consul-cluster-remote-state, tags: first_time_run }
    - { role: vault-cluster-remote-state, tags: first_time_run }
    - { role: jenkins-env-remote-state, tags: first_time_run }
    - { role: prometheus-env-remote-state, tags: first_time_run }
    - { role: grafana-env-remote-state, tags: first_time_run }
    - { role: elasticsearch-cluster-remote-state, tags: first_time_run }
    - { role: logstash-remote-state, tags: first_time_run }
    - { role: filebeat-remote-state, tags: first_time_run }
    - { role: kibana-remote-state, tags: first_time_run }
    - { role: haproxy-lb-remote-state, tags: first_time_run }
    - { role: kms-vault-unseal_key, tags: first_time_run }
    - role: vpc-n-eks
    - role: ssl-create
    - role: consul-cluster
    - role: vault-cluster
      vars:
        local_user_home: "{{ local_user_home }}"
        !unsafe github_sshkey: "{{ github_sshkey }}"
        !unsafe github_ssh_user_email: "{{ github_ssh_user_email }}"
        !unsafe dockerhub_username: "{{ dockerhub_username }}"
        !unsafe dockerhub_password: "{{ dockerhub_password }}"
    - role: jenkins-env
    - role: prometheus-env
    - role: grafana-env
    - role: elasticsearch-cluster
    - role: logstash
    - role: filebeat
    - role: kibana
    - role: haproxy-lb
