---
- hosts: localhost
  tasks: 
    - name: update current haproxy domain_name
      lineinfile:
        regexp: "^domain_name"
        line: "domain_name = \"{{ domain_name }}\""
        path: "{{ playbook_dir }}/../terraform/aws/haproxy-autoscale/terraform.tfvars"
        state: present
      tags: first_time_run
