---
- name: Install helm prometheus chart on aws eks
  terraform:
    binary_path: "/home/{{ lookup('env','USER') }}/bin/terraform"
    project_path: "{{ prometheus_helm_terraform_dir }}"
    state: present
    lock: yes
    backend_config:
      region: "us-east-1"
      bucket: "devopsitall-terraform-remote-state"
      key: "management-helm/prometheus-terraform.tfstate"
      dynamodb_table:  "devopsitall-helm-prometheus-terraform-remote-lock"
      encrypt: "true"
    force_init: true
  register: terraform_run

- name: prometheus helm Terraform output
  debug:
    msg:
      - "{{ terraform_run.command }}"
      - "{{ terraform_run.stdout }}"

