---
- name: Install helm prometheus chart on aws eks
  helm:
    chart:
      #name: prometheus-helm
      source:
        type: git
        location: https://github.com/helm/charts.git
        path: stable/prometheus
      state: present
      #values: "{{ lookup('file', 'prometheus-values-on-kubernetes.yml') | from_yaml }}"
      name: "prometheus-devopsitall"
