---
- name: Create haproxy_lb
  terraform:
    binary_path: "{{ user_home }}/bin/terraform"
    project_path: "{{ haproxy_lb_terraform_dir }}"
    state:        present 
    lock: yes
    backend_config:
      region: "eu-west-1"
      bucket: "devopsitall-terrform-remote-state"
      key: "haproxy-lb-terrform.tfstate"
      dynamodb_table:  "devopsitall-haproxy-autoscale-terrform-remote-lock"
      encrypt:  true
    #plan_file:    "{{ haproxy_lb_terraform_dir }}/devops-it-all-remote-state.tfplan"
    #state_file:   "{{ haproxy_lb_terraform_dir }}/terraform.tfstate"
    force_init: true
  register: terraform_run

- name: Terraform output
  debug:
    msg: 
      - "{{ terraform_run }}"
