---
- name: Get eks workers role arn
  shell: "kubectl -n kube-system get configmap aws-auth -o yaml|sed -n '/mapRoles/,/username: system:node/p' | awk 'NR>4 && NR<6'|awk '{print $2}'"
  register: worker_role

- name: update eks_worker_role_arn variable with current worker role arn
  lineinfile:
    regexp: "^eks_worker_role_arn"
    line: "eks_worker_role_arn = {{ (worker_role.stdout_lines)[0] }}"
    path: "{{ playbook_dir }}/../terraform/aws/haproxy-autoscale/terraform.tfvars"

- name: Create haproxy_lb
  terraform:
    binary_path: "/home/{{ lookup('env','USER') }}/bin/terraform"
    project_path: "{{ haproxy_lb_terraform_dir }}"
    state:        present 
    lock: yes
    backend_config:
      region: "us-east-1"
      bucket: "devopsitall-terraform-remote-state"
      key: "haproxy-lb-terraform.tfstate"
      dynamodb_table:  "devopsitall-haproxy-autoscale-terraform-remote-lock"
      encrypt:  "true"
    force_init: true
  register: terraform_run
